import { buildCases } from "./algorithm-sets";

/**
 * The 57 OLL cases of `docs/source/oll.docx`, in table order. Source of
 * truth — algorithms are copied exactly, including the source's own quirks
 * (cases 26 and 27 share an algorithm; 53 and 54 share a diagram).
 */
export const OLL_CASES = buildCases("oll", [
  "R U2' R2' F R F' U2 R' F R F'",
  "F R U R' U' F' f R U R' U' f'",
  "f R U R' U' f' U' F R U R' U' F'",
  "f R U R' U' f' U F R U R' U' F'",
  "r' U2' R U R' U r",
  "r U2 R' U' R U' r'",
  "r U R' U R U2' r'",
  "r' U' R U' R' U2 r",
  "R U R' U' R' F R2 U R' U' F'",
  "R U R' U R' F R F' R U2' R'",
  "r' R2 U R' U R U2 R' U M'",
  "M' R' U' R U' R' U2 R U' M",
  "r U' r' U' r U r' y' R' U R",
  "R' F R U R' F' R F U' F'",
  "r' U' r R' U' R U r' U r",
  "r U r' R U R' U' r U' r'",
  "R U R' U R' F R F' U2' R' F R F'",
  "r U R' U R U2 r2 U' R U' R' U2 r",
  "M U R U R' U' M' R' F R F'",
  "M U R U R' U' M2' U R U' r'",
  "R U2 R' U' R U R' U' R U' R'",
  "R U2 R2 U' R2 U' R2 U2 R",
  "R2 D R' U2 R D' R' U2 R'",
  "r U R' U' r' F R F'",
  "F' r U R' U' r' F R",
  "R U R' U R U2' R'",
  "R U R' U R U2' R'",
  "r U R' U' M U R U' R'",
  "y R U R' U' R U' R' F' U' F R U R'",
  "F U R U2 R' U' R U2 R' U' F'",
  "R' U' F U R U' R' F' R",
  "R U B' U' R' U R B R'",
  "R U R' U' R' F R F'",
  "R U R2' U' R' F R U R U' F'",
  "R U2' R2' F R F' R U2' R'",
  "R' U' R U' R' U R U l U' R' U x",
  "F R U' R' U' R U R' F'",
  "R U R' U R U' R' U' R' F R F'",
  "L F' L' U' L U F U' L'",
  "R' F R U R' U' F' U R",
  "R U R' U R U2' R' F R U R' U' F'",
  "R' U' R U' R' U2 R F R U R' U' F'",
  "R' U' F' U F R",
  "f R U R' U' f'",
  "F R U R' U' F'",
  "R' U' R' F R F' U R",
  "F' L' U' L U L' U' L U F",
  "F R U R' U' R U R' U' F'",
  "r U' r2' U r2 U r2' U' r",
  "r' U r2 U' r2' U' r2 U r'",
  "f R U R' U' R U R' U' f'",
  "R' U' R U' R' U y' R' U R B",
  "r' U' R U' R' U R U' R' U2 r",
  "r U R' U R U' R' U R U2' r'",
  "y R' F R U R U' R2' F' R2 U' R' U R U R'",
  "r' U' r U' R' U R U' R' U R r' U r",
  "R U R' U' M' U R U' r'",
]);
